src/views/auth_view.py
from flask import Blueprint, request, render_template, session, redirect, url_for,Response
from models.user_model import UserModel
from utils.security import Security


auth_blueprint = Blueprint("auth_view", __name__)


@auth_blueprint.route("/login", methods=["GET", "POST"])
def login():
    # get html
    if request.method == "GET":
        return render_template("login.html")
    # login
    try:
        email = request.form["username"]
        password = request.form["password"]
        users = UserModel.objects(
            email=email, password=Security.hash(password))
        if len(users) > 0:
            user = users[0]
            session["current_user"] = {
                "id": str(user.id),
                "first_name": user.first_name,
                "last_name": user.last_name,
                "email": user.email,
            }
            return redirect(url_for("home_view.render"))
        return render_template("login.html", error="Wrong credentials")
    except Exception as err:
        print(err)
        return render_template("login.html", error=str(err))


@auth_blueprint.route("/register", methods=["GET", "POST"])
def register():

    # get html
    if request.method == "GET":
        return render_template("register.html")
    # login
    try:
        email = request.form.get("email")
        user = UserModel.objects(email=email)
        if len(user) > 0:
            return render_template("register.html", error="User with this email exists.")
        first_name = request.form.get("firstName")
        last_name = request.form.get("lastName")
        password = request.form.get("password")
        UserModel(first_name=first_name, last_name=last_name,
                  email=email, password=Security.hash(password)).save()
        user = UserModel.objects.get(email=email)
        if user:
            session["current_user"] = {
                "id": str(user.id),
                "first_name": user.first_name,
                "last_name": user.last_name,
                "email": user.email,
            }
            return redirect(url_for("home_view.render"))
        return render_template("register.html", error="Something went wrong, and user haven't created.")
    except Exception as err:
        return render_template("register.html", error=str(err))


@auth_blueprint.route("/logout",methods=["DELETE"])
def logout():
    session.clear()
    # return to client success
    return Response(status=200)

src/views/dashboard_view.py
from flask import Blueprint, request, render_template, session, redirect, jsonify, Response
import requests
from models.url_model import UrlModel
from models.user_model import UserModel
from mongoengine import DoesNotExist
from random import randint


dashboard_blueprint = Blueprint("dashboard_view", __name__)


@dashboard_blueprint.route("/dashboard")
def render():
    user = session["current_user"]
    urls_models = UrlModel.objects(user=user["id"])
    colors = []
    for i in range(len(urls_models)):
        colors.append([randint(0, 255), randint(0, 255), randint(0, 255)])
    return render_template("dashboard.html", urls_data=urls_models, colors=colors)


@dashboard_blueprint.route("/urls-stat")
def stat():
    user = session["current_user"]
    urls_models = UrlModel.objects(user=user["id"])
    data = [{
        "id": str(url_model.id),
        "shortUrl": url_model.short_url,
        "fullUrl": url_model.full_url,
        "visits": url_model.enters
    } for url_model in urls_models]
    return jsonify(data)

src/views/home_view.py
from flask import Blueprint, request, render_template, session, redirect, jsonify, Response
import requests
from random import choice
from string import ascii_letters, digits
from models.url_model import UrlModel
from models.user_model import UserModel
from mongoengine import DoesNotExist


home_blueprint = Blueprint("home_view", __name__)


@home_blueprint.route("/")
@home_blueprint.route("/home")
def render():
    return render_template("home.html")


@home_blueprint.route("/geturl", methods=["POST"])
def get_url():
    url = request.form.get("url")
    response = requests.get(url, allow_redirects=False)
    if response.is_redirect or response.status_code == 302:
        url = response.headers['Location']
    return jsonify({"url": url})


@home_blueprint.route("/short", methods=["POST"])
def short_it():
    user_id = session["current_user"]["id"]
    user_model = UserModel.objects.get(id=user_id)
    full_url = request.form.get("url")
    chars = ascii_letters+digits
    short_url = None
    run_again = True
    while run_again:
        short_string = ''.join(choice(chars) for _ in range(6))
        short_url = f"http://{request.host}/{short_string}"
        if (len(UrlModel.objects(short_url=short_url)) == 0):
            url_model = UrlModel(short_url=short_url,
                                 full_url=full_url, user=user_model).save()
            run_again = False
    return jsonify({"url": short_url})


@home_blueprint.route("/<url_part>")
def redirect_to(url_part):
    try:
        if url_part != "favicon.ico":
            short_url = f"http://{request.host}/{url_part}"
            url_model = UrlModel.objects.get(short_url=short_url)
            UrlModel.objects(short_url=short_url).update_one(
                enters=url_model.enters+1)
            return redirect(url_model.full_url)
        return Response(status=200)
    except DoesNotExist:
        return render_template("404.html")

src/templates/dashboard.html
{% extends "layout.html" %}
{% block title %} Page not found {% endblock title %}
{% block content %}
<div class="dashboard">
    <div class="container">
        <div class="row">
            <div class="col-md-6" id="urlsContainer">
            </div>
            <div class="col-md-6">
                <canvas id="urlsPie"></canvas>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

src/templates/footer.html
<footer>
    All rights reserved by Stanislav Mestechkin
</footer>

src/templates/header.html
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('home_view.render') }}">Shorty</a>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{{ url_for('home_view.render') }}">Home <span
                        class="sr-only">(current)</span></a>
                {% if user %}
                <a class="nav-item nav-link" href="{{ url_for('dashboard_view.render') }}" id="dashboardLink">Dashboard</a>
                {% endif %}

            </div>
        </div>
        <div class="col-md-2 col-sm-3 col-xs-4">
            <div class="container">
                {% if user %}
                <div class="row">
                    <div class="col-sm-12" id="helloUser">Hello {{user.first_name}} {{user.last_name}}</div>
                </div>
                <div class="row">
                    <div class="col-sm-12" id="auth">
                        <span onclick="logout()">Sign out</span>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </nav>

</header>

src/templates/home.html
{% extends "layout.html" %}
{% block title %} Home {% endblock title %}
{% block content %}
<div class="home">
    <div class="card">
        <div class="card-body" name="reverse">
            <h5 class="card-title">Get real URL from shortened URL</h5>
            <p class="card-text">Just enter url...</p>
            <div>
                <div class="form-group mx-sm-3 mb-2">
                    <label for="url" class="sr-only">Shortened URL</label>
                    <input type="url" class="form-control" id="url">
                </div>
                <div class="form-group mx-sm-3 mb-2">
                    <label for="result" class="sr-only">Real URL:</label>
                    <output id="result" class="form-control"></output>
                </div>
                <button class="btn btn-dark mb-2" id="reverse">Get real URL</button>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-body" name="reverse">

            {% if user %}
            <div>
                <div class="form-group mx-sm-3 mb-2">
                    <label for="fullUrl" class="sr-only">URL</label>
                    <textarea class="form-control" id="fullUrl"></textarea>
                </div>
                <div class="form-group mx-sm-3 mb-2">
                    <label for="shortedUrl" class="sr-only">Real URL:</label>
                    <output id="shortedUrl" class="form-control"></output>
                </div>
                <button class="btn btn-dark mb-2" id="shortIt">Short It!</button>
            </div>
            {% else %}
            <h5 class="card-title">Want to generate short URLs?</h5>
            <p class="card-text">Please sign in and get more futures...</p>
            <h6>It free!</h6>
            <a href="{{url_for('auth_view.login')}}" class="btn btn-outline-dark">Sign in</a>
            <a href="{{url_for('auth_view.register')}}" class="btn btn-outline-dark">Sign up</a>            
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

src/templates/layout.html
{% set user = session.get("current_user") %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js">
    </script>
</head>

<body>
    {% include "header.html" %}
    <main>
        {% block content %}{% endblock content %}
    </main>
    {% include "footer.html" %}
    <script src="{{url_for('static', filename='js/main.js')}}"></script>
</body>

</html>

src/templates/login.html
{% extends "layout.html" %}
{% block title %} Sign in {% endblock title %}
{% block content %}
<div class="container">
    <form class="col-lg-6 col-md-8 col-sm-10 col-xs-12 login-form" method="post">
        <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" class="form-control" id="username" name="username">
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" class="form-control" id="password" name="password">
        </div>
        <div class="row">
            <div class="col-sm-6">
                <button class="btn btn-md btn-dark">Sign in</button>
            </div>
            <div class="col-sm-6">
                <a href="{{ url_for('auth_view.register') }}" class="btn btn-md btn-outline-dark">Sign up</a>
            </div>
        </div>
        {% if error %}
        <div>
            <div class="alert alert-warning"">{{error}}</div>
            
        </div>
        {% endif %}
    </form>
</div>
{% endblock content %}

src/templates/register.html
{% extends "layout.html" %}
{% block title %} Sign up {% endblock title %}
{% block content %}
<div class="container">
    <form class="col-lg-6 col-md-8 col-sm-10 col-xs-12 register-form" method="post">
        <div class="form-group">
            <label for="firstName">First Name:</label>
            <input type="text" class="form-control" id="firstName" name="firstName" placeholder="First Name">
        </div>
        <div class="form-group">
            <label for="lastName">Last Name:</label>
            <input type="text" class="form-control" id="lastName" name="lastName" placeholder="Last Name">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail">Email:</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Email">
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
        </div>
        <div>
            <button class="btn btn-md btn-dark">Sign up</button>
        </div>
        {% if error %}
        <div>
            <div class="alert alert-warning"">{{error}}</div>
            
        </div>
        {% endif %}
</div>
</form>
</div>
{% endblock content %}